---
- name: "create directory {{ install_path }}/opennms"
  file:  path="{{ install_path }}/opennms" state=directory

- name: "copy and extract OpenNMS archive"
  unarchive: src={{ filename_opennms }} dest="{{ install_path }}/opennms" copy=yes

- name: "find java version"
  shell: "{{ install_path }}/opennms/bin/runjava -s"

- name: "setup database"
  shell: "{{ install_path }}/opennms/bin/install -dis"

- name:  "set link for init script"
  file: state=link src="{{install_path }}/opennms/bin/opennms" path=/etc/init.d/opennms

- name:  "install init script"
  service: name=opennms enabled=yes
