---
- name: "OpenNMS: create directory /opt/opennms"
  file:  path=/opt/opennms state=directory

- name: "OpenNMS: copy and extract"
  unarchive: src={{ filename_opennms }} dest=/opt/opennms copy=yes

- name: "OpenNMS: find java version"
  shell: /opt/opennms/bin/runjava -s

- name: "OpenNMS: setup database"
  shell: /opt/opennms/bin/install -dis

- name:  "OpenNMS: set link for init script"
  file: state=link src=/opt/opennms/bin/opennms path=/etc/init.d/opennms

- name:  "OpenNMS: install init script"
  service: name=opennms enabled=yes
