---
- name: "create directory {{ install_path }}/opennms"
  file:  path="{{ install_path }}/opennms" state=directory

- name: "copy and extract OpenNMS archive"
  unarchive: src={{ filename_opennms }} dest="{{ install_path }}/opennms" copy=yes

- name: "find java version"
  shell: "{{ install_path }}/opennms/bin/runjava -s"

- name: "setup database"
  shell: "{{ install_path }}/opennms/bin/install -dis"

- name: "check if systemd manages services"
  find: pattern="system" paths="/etc/systemd" file_type=directory
  register:  check_systemd

- include: install-initd-script.yml
  when: "{{ check_systemd.matched }}  != 1"

- include: install-systemd-script.yml
  when: "{{ check_systemd.matched }}  == 1"
