---
# OpenNMS single node
- hosts: all
  remote_user: root
  vars_prompt:
  - name: "filename_jicmp"
    prompt: "jicmp archive file"
    default: "./repository/jicmp-1.4.4.tar.gz"
    private: no
  - name: "filename_jicmp6"
    prompt: "jicmp6 archive file"
    default: "./repository/jicmp6-1.2.3.tar.gz"
    private: no
  - name: "filename_jdk"
    prompt: "Oracle Java JDK archive file"
    default: "./repository/jdk-8u74-linux-x64.tar.gz"
    private: no
  - name: "filename_opennms"
    prompt: "OpenNMS archive file"
    default: "./repository/opennms-17.0.0.tar.gz"
    private: no
  - name: "install_path"
    prompt: "path for installing"
    default: "/opt"
    private: no
  - name: "ntp_server"
    prompt: "NTP: set NTP server"
    default: "pool.ntp.org"
    private: no
  - name: "snmpd_community"
    prompt: "SNMP: set community"
    default: "public"
    private: no
  - name: "snmpd_location"
    prompt: "SNMP: set SysLocation"
    default: "Datacenter"
    private: no
  - name: "snmpd_contact"
    prompt: "SNMP: set SysContact"
    default: "Support"
    private: no
  roles:
    - precheck.archive
    - package_updates
    - snmp
    - ntpdate
    - postgres
    - java
    - jicmp
    - opennms.archive
