---
- include: "{{ ansible_os_family }}.yml"

- name: "check availability of NTP server"
  command: ntpdate {{ ntp_server }}
  register: ntp_result
  ignore_errors: True

- name: "install ntpdate cronjob"
  cron: name="ntp sync" minute="0" job="ntpdate {{ ntp_server }} > /dev/null"
  when: "'no servers can be used' not in ntp_result.stderr"
