---
- name: "check if local hostname is in /etc/hosts"
  command: getent hosts {{ ansible_hostname }}
  register: check_hosts
  ignore_errors: True

- name: "insert local hostname in /etc/hosts"
  lineinfile: dest=/etc/hosts insertafter=EOF line="127.0.0.1  {{ ansible_hostname }}"
  when: check_hosts.rc != 0

- name: "create directory {{ install_path }}/opennms"
  file:  path="{{ install_path }}/opennms" state=directory

- name: "copy and extract OpenNMS archive"
  unarchive: src={{ filename_opennms }} dest="{{ install_path }}/opennms" copy=yes

- name: "find java version"
  shell: "{{ install_path }}/opennms/bin/runjava -s"

- name: "setup database"
  shell: "{{ install_path }}/opennms/bin/install -dis"

- name: "check if systemd manages services"
  find: pattern="system" paths="/etc/systemd" file_type=directory
  register:  check_systemd

- include: install-initd-script.yml
  when: ansible_os_family == "Debian"

- include: install-systemd-script.yml
  when: ansible_os_family == "RedHat"  or ansible_os_family == "Suse"
