---
opennms_deb_key: 'http://debian.opennms.org/OPENNMS-GPG-KEY'
opennms_deb_repos:
  - 'deb http://debian.opennms.org stable main'
  - 'deb-src http://debian.opennms.org stable main'
opennms_deb_install_path: '/usr/share/opennms'

opennms_rpm_repos: 'http://yum.opennms.org/repofiles/opennms-repo-stable-rhel7.noarch.rpm'
opennms_rpm_install_path: '/opt/opennms'
