---
- name: "check if local hostname is in /etc/hosts"
  command: getent hosts {{ ansible_hostname }}
  register: check_hosts
  ignore_errors: True

- name: "insert local hostname in /etc/hosts"
  lineinfile: dest=/etc/hosts insertafter=EOF line="127.0.0.1  {{ ansible_hostname }}"
  when: check_hosts.rc != 0

- include: "{{ ansible_os_family }}.yml"

- name: "find java version"
  shell: "{{ install_path }}/bin/runjava -s"

- name: "setup database"
  shell: "{{ install_path }}/bin/install -dis"
