---
- include: "{{ ansible_os_family }}.yml"

- name: "find pg_hba.conf"
  find: patterns="pg_hba.conf" recurse=yes paths={{ pg_dirs }}
  register: pg_hba_conf

- name: "setup database access"
  replace: dest={{ pg_hba_conf.files.0.path }}
           regexp={{ item }} replace='\1trust'
           backup=yes
  with_items:
  - '^(host.*?all.*?all.*?127.*?)(md5)$'
  - '^(host.*?all.*?all.*?::1/128.*?)(md5)$'
  - '^(local.*?all.*?all.*?)(peer)$'
  when: "{{ pg_hba_conf.matched }}  == 1"

- name: "restart PostgreSQL"
  service: name=postgresql state=restarted
