---
- name: "PostgreSQL: install database server"
  apt: name=postgresql

- name: "PostgreSQL: setup database access: local"
  replace: dest=/etc/postgresql/9.3/main/pg_hba.conf 
           regexp='^(local.*?all.*?all.*?)(peer)$' replace='\1trust'
           backup=yes

- name: "PostgreSQL: setup database access: host 127.0.0.1"
  replace: dest=/etc/postgresql/9.3/main/pg_hba.conf 
           regexp='^(host.*?all.*?all.*?127.*?)(md5)$' replace='\1trust'
           backup=yes

- name: "PostgreSQL: setup database access: host ::1/128"
  replace: dest=/etc/postgresql/9.3/main/pg_hba.conf 
           regexp='^(host.*?all.*?all.*?::1/128.*?)(md5)$' replace='\1trust'
           backup=yes

- name: "PostgreSQL: restart PostgreSQL"
  service: name=postgresql state=restarted
